### ISSUE TITLE
Fountain.js - A JavaScript Fountain parser

### ISSUE THREAD

**Issue by mattdaly** [nyousefi/Fountain#1]
Apologies for using the issues feature to do this but it seemed like the best place to notify watchers of the project.

I've been working on a JavaScript parser for Fountain that some users might be interested in. The parser and code itself are available on my GitHub page (http://github.com/mattdaly/Fountain.js) and a converter application is set up on a GitHub Pages page (http://mattdaly.github.com/Fountain.js/). The parser itself is still being optimized (I approach it a little differently to the official Obj-C code), and the css styling for the formatted HTML needs some tweaking.

Right now, it's just the parser and HTML formatter/converter. I have an analyser in the works that'll pump out a bunch of character, scene and time of day (and more) information. I'm also working on better page rendering.

If anyone wants to contribute please feel free, or pass on any suggestions or problems you encounter.

**Comment by 7fe** [comment]
@mattdaly I noticed it hasn't been updated in 6 years.

Do you know of any alternatives if yours doesn't work well?

**Comment by laurent22** [comment]
@limeb, I'm also looking for a Fountain JS lib for my application. Have you found a good one by any chance?
