### ISSUE TITLE
Spec shouldn't rely on trailing whitespace

### ISSUE THREAD

**Issue by stuartpb** [nyousefi/Fountain#3]
(Is this the place to raise issues with Fountain's syntax? Anyway, I'm doing it.)

Looking over http://fountain.io/syntax I notice that the suggested way to avoid automatic categorization is to include **two trailing spaces** on a line.

Relying on trailing whitespace is bad, for a few reasons- not the least of which is that lots of stuff, including the editor I use every day, is set to **strip trailing whitespace** on file save (preserving trailing whitespace is a great way to introduce infuriating, invisible diffs). Making the non-syntactic line breaks whitespace-indistinguishable also just plain makes the Fountain doc hard to read - if line breaks are my single cue for the end of dialogue, I'm going to be totally thrown when they're to mean something completely different.

Maybe add another rule that lets lines end at the last printable character? I'd suggest stripping empty pairs of parentheses at the end of a line, like this:

``` fountain
DEALER
Ten.
Four.
Dealer gets a seven.
()
Hit or stand sir?
```

Or this:

``` fountain
ROBERT
But, wait- if I'm not- and this is- but that's- oh my-

IN A FLASH OF SMOKE, ROBERT CEASES TO BE A CHARACTER. ()
This was his own fault for messing with the Syntax of Life.
```

I'm thinking empty parentheses because it kind of resembles what it kind of represents, a completely invisible, nigh-imperceptible, meta `(beat)`.

If, for some unfathomable reason, a line needs an empty set of parentheses at the end, they could be backslash escaped, like how ****\*non-emphatic asterisks\_\_*** are:

``` fountain
NEO, bent over the terminal, finally realizing his destiny, uses every last ounce
of his strength to deliver the last salvation of humanity:

    (XCU on screen)
  Matrix.free\(\)
```

Also, continuing from that last idea, it should be possible (I don't know if this works with the current spec or not) for an action to start with an escaped leading right-angle-bracket, so we can represent things like actions at command prompts with:

``` fountain
\> new Matrix.enslavement(Machines)
```

**Comment by strokirk** [comment]
I'd like to revive this. Having some way of explicitly marking dialogue would be really useful. Trailing space is a little tricky to enforce.

**Comment by stuartpb** [comment]
For what it's worth, in Markdown, the alternative to the thing whitespace offers is to explicitly write `<br>` (as the canonical Markdown implementation is designed to intermingle with HTML); perhaps `<br>` could be explicitly recognized as a token in Fountain?
